// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4gmMi43eKXOE_00WT3tftCyV-1-AxrLo',
    appId: '1:67049626395:web:221554e9052d7e3db0d1be',
    messagingSenderId: '67049626395',
    projectId: 'radio-adventista-reforma',
    authDomain: 'radio-adventista-reforma.firebaseapp.com',
    databaseURL: 'https://radio-adventista-reforma-default-rtdb.firebaseio.com',
    storageBucket: 'radio-adventista-reforma.firebasestorage.app',
    measurementId: 'G-27R2JRKFV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbNFmJvoyV1Qitexa6ixlmhvUkwBuA0M',
    appId: '1:67049626395:android:bcf4f65de8442caab0d1be',
    messagingSenderId: '67049626395',
    projectId: 'radio-adventista-reforma',
    databaseURL: 'https://radio-adventista-reforma-default-rtdb.firebaseio.com',
    storageBucket: 'radio-adventista-reforma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwsJ3BYeB4-H5NFr4bZ5HoxlY6lAHeHBM',
    appId: '1:67049626395:ios:067275d3ca23d773b0d1be',
    messagingSenderId: '67049626395',
    projectId: 'radio-adventista-reforma',
    databaseURL: 'https://radio-adventista-reforma-default-rtdb.firebaseio.com',
    storageBucket: 'radio-adventista-reforma.firebasestorage.app',
    iosBundleId: 'com.example.radioZenoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwsJ3BYeB4-H5NFr4bZ5HoxlY6lAHeHBM',
    appId: '1:67049626395:ios:067275d3ca23d773b0d1be',
    messagingSenderId: '67049626395',
    projectId: 'radio-adventista-reforma',
    databaseURL: 'https://radio-adventista-reforma-default-rtdb.firebaseio.com',
    storageBucket: 'radio-adventista-reforma.firebasestorage.app',
    iosBundleId: 'com.example.radioZenoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4gmMi43eKXOE_00WT3tftCyV-1-AxrLo',
    appId: '1:67049626395:web:8ddf53e7b2356f14b0d1be',
    messagingSenderId: '67049626395',
    projectId: 'radio-adventista-reforma',
    authDomain: 'radio-adventista-reforma.firebaseapp.com',
    databaseURL: 'https://radio-adventista-reforma-default-rtdb.firebaseio.com',
    storageBucket: 'radio-adventista-reforma.firebasestorage.app',
    measurementId: 'G-STQEYKS1Z7',
  );

}